const fs = require('fs');
const path = require('path');

const enDir = 'd:\\Iworkspaces\\alize-template\\en';

const globalDict = {
    'Tổng\\s*Quan': 'Overview',
    'Giá\\s*Trị': 'Values',
    'Vị\\s*Trí': 'Location',
    'Kiến\\s*Trúc': 'Architecture',
    'Tiện\\s*Ích': 'Amenities',
    'Dịch\\s*Vụ': 'Services',
    'Mặt\\s*Bằng': 'Floor Plans',
    'Không\\s*Gian': 'Gallery',
    'Nhận\\s*Đặc Quyền': 'Get Privileges',
    'Bảo Mật': 'Privacy Policy',
    'Điều Khoản': 'Terms of Service',
    'Chạm vào đỉnh cao không gian sống. Tuyệt tác kiến trúc ALIZE - Vùng đất dành cho sự tĩnh tại và phong cách\\s*sống vô song.': 'Touch the pinnacle of living. ALIZE architectural masterpiece - A land for tranquility and unparalleled lifestyle.',
    'Chạm vào đỉnh cao không gian sống. Tuyệt tác kiến trúc ven biển dành cho sự tĩnh tại và phong cách\\s*sống vô song.': 'Touch the pinnacle of living. Coastal architectural masterpiece for tranquility and unparalleled lifestyle.',
    'Đăng\\s*Ký Gặp Gỡ': 'Register to Meet',
    'Trở Thành Chủ Nhân Của<br/>\\s*<span class="italic font-serif text-champagne/60">Các Đặc Quyền Vượt Tầm</span>': 'Become the Owner of<br/> <span class="italic font-serif text-champagne/60">Transcendent Privileges</span>',
    'Liên hệ riêng tư': 'Private Contact',
    'Yêu Cầu Bộ Hồ Sơ Thiết Kế<br/>\\s*<span class="italic font-serif text-champagne/60">& Báo Giá Chi Tiết</span>': 'Request Design Dossier<br/> <span class="italic font-serif text-champagne/60">& Detailed Quote</span>',
    'Phân Phối Chính Thức': 'Official Distribution',
    'Trọn Vẹn Bầu Trời': 'The Entire Sky',
    'Tầng Không Sky Penthouse': 'Sky Penthouse',
    'Tổ ấm lý tưởng': 'Ideal Home',
    'Căn Hộ 2 Phòng Ngủ': '2-Bedroom Apartment',
    'Tối giản tinh tế': 'Exquisite Minimalism',
    'Studio & 1 Phòng Ngủ': 'Studio & 1-Bedroom',
    'Bộ Sưu Tập Giới Hạn': 'Limited Collection',
    'Hầm Đỗ Xe Thông Minh': 'Smart Parking Basement',
    'Dưới Lòng Đất': 'Underground',
    'Đại Sảnh & Shophouse Du Lịch': 'Grand Lobby & Tourist Shophouse',
    'Tầng 1': 'Floor 1',
    'Thương mại và Services Khối Đế': 'Podium Commerce & Services',
    'Tầng 2 – 4': 'Floor 2 – 4',
    'Tầng Amenities Đỉnh Cao \\(Amenities Deck\\)': 'Pinnacle Amenities Deck',
    'Cao 6.0m': '6.0m Height',
    'Tầng 5': 'Floor 5',
    'Căn Hộ Hạng Sang \\(Luxury Apartments\\)': 'Luxury Apartments',
    'Cao 3.5m / Tầng': '3.5m Height / Floor',
    'Tầng 6 – 25': 'Floor 6 – 25',
    'Cấu Trúc <br />\\s*<span class="italic font-serif text-pearl-white/70">Phân Phân Tầng</span>': 'Structure <br /> <span class="italic font-serif text-pearl-white/70">Floor by Floor</span>',
    'Mặt Cắt Gallery': 'Gallery Cross Section',
    'BẢN ĐỒ KIẾN TẠO THƯỢNG LƯU': 'MAP OF ELITE CREATION',
    'Đăng Ký Khám Phá': 'Register to Discover',
    'Đăng Ký Discover': 'Register to Discover',
    'Từ hồ bơi vô cực ngắm bình\\s*minh trên biển đến không gian riêng tư của phòng giải trí Cigar & Wine.': 'From the infinity pool watching the sunrise over the sea to the private space of the Cigar & Wine entertainment lounge.',
    'Phân Phân Khu\\s*01': 'Zone 01',
    'Phân Phân Khu\\s*02': 'Zone 02',
    'Phân Phân Khu\\s*03': 'Zone 03',
    'Dấu\\s*Ấn Architecture': 'Architectural Imprint',
    'Sành\\s*Điệu Gallery Sống': 'Stylish Living Gallery',
    'Trực Quang\\s*Sinh Động': 'Vivid Visuals',
    'Ngoại Thất': 'Exterior',
    'Ban công góc': 'Corner Balcony',
    'Góc Xoay Bầu Trời': 'Sky Twist Angle',
    'Hồ Bơi Lớn': 'Large Pool',
    'Shophouse Khối Đế': 'Podium Shophouse',
    'GIÁ TRỊ TRUYỀN ĐỜI': 'LIFELONG VALUES',
    'TUYỆT TÁC ĐẦU TƯ<br />\\s*<span class="font-serif italic font-light text-pearl-white/90">Vượt Thời Gian</span>': 'INVESTMENT MASTERPIECE<br /> <span class="font-serif italic font-light text-pearl-white/90">Beyond Time</span>',
    'ALIZE Đà Nẵng không đơn thuần là một dự án bất động sản, mà là một khối tài sản mang tính biểu tượng, tích lũy giá trị phi thường qua thời gian nhờ 3 trụ cột vững chắc.': 'ALIZE Da Nang is not merely a real estate project, but an iconic asset, accumulating extraordinary value over time thanks to 3 solid pillars.',
    'Tầm Nhìn <br/>\\s*<span class="italic font-serif text-pearl-white/70">Trực Diện Biển</span>': 'Direct Sea <br/> <span class="italic font-serif text-pearl-white/70">Facing View</span>',
    'Trong bất động sản hạng sang, tầm nhìn là thứ định đoạt đẳng cấp. Đặc biệt với bất động sản ven biển, những căn hộ sở hữu mặt tiền thoáng đãng hướng ra đại dương luôn lọt vào mắt xanh của giới tinh hoa.': 'In luxury real estate, the view dictates the class. Especially with coastal real estate, apartments possessing airy frontages facing the ocean always catch the eyes of the elite.',
    'Sở hữu mặt tiền đại lộ Võ Nguyên Giáp, tầm nhìn vô cực trực diện bãi biển Mỹ Khê - một trong những trục biển tỷ đô giá trị bậc nhất miền Trung. View biển Panorama ôm trọn hoàng hôn và bình minh tuyệt mĩ.': 'Owning the frontage of Vo Nguyen Giap Avenue, infinity views directly facing My Khe Beach - one of the most valuable billion-dollar coastal axes in the Central region. Panoramic view embraces magnificent sunsets and sunrises.',
    'Tăng Giá <br/>\\s*<span class="italic font-serif text-pearl-white/70">Bền Vững</span>': 'Sustainable <br/> <span class="italic font-serif text-pearl-white/70">Appreciation</span>',
    'Không phụ thuộc quá lớn vào chu kỳ thị trường, bất động sản hữu hạn lõi trung tâm luôn có xu hướng thiết lập mặt bằng giá mới theo thời gian nhờ sự phát triển của hạ tầng và khan hiếm của quỹ đất.': 'Not overly dependent on market cycles, limited core central real estate always tends to establish new price levels over time due to infrastructure development and land scarcity.',
    '01. Quỹ Đất Hữu Hạn': '01. Limited Land Fund',
    'Nằm trong lõi du lịch đô thị. Diện tích ven biển Mỹ Khê đã được quy hoạch kín, dư địa phát triển cho các dự án mới gần như bằng không.': 'Located in the core of urban tourism. The My Khe coastal area has been fully planned, development room for new projects is almost zero.',
    '02. Bảo Toàn Vốn Gốc': '02. Capital Preservation',
    'Kênh giữ tiền an toàn và hiệu quả, tài sản để dành và truyền đời với giá trị không ngừng thặng dư cho thế hệ sau.': 'A safe and efficient channel to hold money, an asset to save and pass down with unceasingly surplus value for the next generation.',
    'Khả Năng Khai Thác <br/>\\s*<span class="italic font-serif text-pearl-white/70">Cho Thuê Ngoạn Mục</span>': 'Spectacular <br/> <span class="italic font-serif text-pearl-white/70">Rental Potential</span>',
    'Hệ Sinh Thái Du Lịch': 'Tourism Ecosystem',
    'Được cộng hưởng mạnh mẽ từ sinh thái du lịch của Đà Nẵng, nơi tổ chức các lễ hội quốc tế lớn thu hút hàng triệu du khách.': 'Strongly resonated by the tourism ecosystem of Da Nang, where major international festivals are held attracting millions of visitors.',
    'Lưu Trú Cao Cấp': 'High-end Accommodation',
    'Mô hình căn hộ nghỉ dưỡng hạng sang dễ dàng áp dụng chuẩn hóa vận hành dịch vụ quốc tế, đáp ứng giới chuyên gia nước ngoài.': 'The luxury resort apartment model easily adopts standardized international service operations, meeting the needs of foreign experts.',
    'Dòng Tiền Đều Đặn': 'Steady Cash Flow',
    'Tạo lập nguồn thu nhập thụ động bền vững ngoài việc trông chờ vào sự gia tăng giá trị vốn của tài sản theo thời gian.': 'Creating a sustainable passive income source besides expecting capital appreciation of the asset over time.',
    'Phân Tích Bảng Giá & <br/>\\s*<span class="italic font-serif text-champagne/60">Chính Sách Thanh Toán</span>': 'Price Analysis & <br/> <span class="italic font-serif text-champagne/60">Payment Policies</span>',
    'Thông Tin Đầu Tư': 'Investment Information',
    'DỊCH VỤ KIM CƯƠNG': 'DIAMOND SERVICES',
    'ĐẶC QUYỀN <br />\\s*<span class="font-serif italic font-light text-pearl-white/90">Sống Thượng Lưu</span>': 'PRIVILEGES <br /> <span class="font-serif italic font-light text-pearl-white/90">Of Elite Living</span>',
    'Phượt qua mọi giới hạn của dịch vụ thông thường, ALIZE cung cấp một hệ sinh thái chăm sóc cá nhân vô song. Nơi mọi nhu cầu dù là nhỏ nhất của bạn đều được đáp ứng bởi đội ngũ tinh anh vận hành theo chuẩn mực quốc tế khắt khe.': 'Surpassing all limits of ordinary services, ALIZE offers an unparalleled personal care ecosystem. Where even your smallest needs are met by an elite team operating under strict international standards.',
    'Chăm Sóc Độc Bản 01': 'Unique Care 01',
    'Quản Gia <br />\\s*<span class="italic font-serif text-pearl-white/70">Tư Nhân 24/7</span>': 'Private <br /> <span class="italic font-serif text-pearl-white/70">Butler 24/7</span>',
    'Mỗi một phân khu căn hộ ALIZE đều có sự túc trực 24/7 của đội ngũ quản gia chuyên nghiệp, được đào tạo bởi hệ thống cung ứng dịch vụ quản lý khách sạn danh tiếng toàn cầu. Sự ân cần tĩnh lặng vượt xa kỳ vọng.': 'Every ALIZE apartment zone has the 24/7 attendance of a professional butler team, trained by the globally renowned hotel management service supply system. The silent attentiveness exceeds expectations.',
    'Cung cấp dịch vụ đặt lịch tiệc tùng, sự kiện cá nhân.': 'Provide booking services for private parties and events.',
    'Sắp xếp lịch trình đưa đón xe hạng sang tại sảnh.': 'Arrange luxury car pick-up and drop-off schedules at the lobby.',
    'Bảo trì căn hộ định kỳ và vệ sinh không gian cá nhân theo yêu cầu khắt khe nhất.': 'Periodic apartment maintenance and personal space cleaning according to the strictest requirements.',
    'Chăm Sóc Độc Bản 02': 'Unique Care 02',
    'An Ninh <br />\\s*<span class="italic font-serif text-pearl-white/70">Khép Kín Tư Mật</span>': 'Private <br /> <span class="italic font-serif text-pearl-white/70">Closed Security</span>',
    'Quyền riêng tư là món trang sức xa xỉ nhất của giới tỷ phú. ALIZE thấu hiểu điều này và trang bị một hệ thống an ninh tối tân, đảm bảo không một ai có thể xâm phạm không gian cá nhân của bạn.': 'Privacy is the most luxurious jewelry of billionaires. ALIZE understands this and is equipped with a state-of-the-art security system, ensuring no one can invade your personal space.',
    'Hệ thống nhận diện vòng mống mắt và thẻ từ định danh được thiết lập riêng cho từng chủ sở hữu. Cầu thang máy thông minh dẫn thẳng lên sảnh chờ căn hộ riêng mà không chia sẻ băng thông với bất kỳ đối tượng nào khác.': 'The iris recognition and ID magnetic card system is set up individually for each owner. Smart elevators lead directly to the private apartment lobby without sharing bandwidth with anyone else.',
    '"Sự yên bình tuyệt đối cho những tâm hồn đã chạm định danh."': '"Absolute peace for souls who have touched their identity."',
    'Chăm Sóc Độc Bản 03': 'Unique Care 03',
    'Trải Nghiệm <br/>\\s*<span class="italic font-serif text-pearl-white/70">Nghệ Thuật Ẩm Thực</span>': 'Experience <br/> <span class="italic font-serif text-pearl-white/70">Culinary Arts</span>',
    'Đầu Bếp Michelin': 'Michelin Chefs',
    'Những đầu bếp trứ danh từ hệ thống nhà hàng Michelin luôn sẵn sàng tại gia để đánh thức vị giác của bạn bằng những kiệt tác nghệ thuật ẩm thực tinh hoa.': 'Renowned chefs from the Michelin restaurant system are always ready at home to awaken your taste buds with masterpieces of elite culinary art.',
    'Nguyên Liệu Thượng Hạng': 'Premium Ingredients',
    'Mạng lưới cung ứng siêu cao cấp đảm bảo Bào Ngư, Nấm Truffle, Bò Wagyu hay Saffon quý hiếm luôn có mặt trong phòng bếp của bạn chỉ bằng một cú điện thoại.': 'An ultra-premium supply network ensures Abalone, Truffle Mushrooms, Wagyu Beef or rare Saffron are always available in your kitchen with just a phone call.',
    'Wine Tasting Khép Kín': 'Private Wine Tasting',
    'Tổ chức những buổi thử rượu vang riêng tư cùng các Sommelier \\(Chuyên gia nếm rượu vang\\), trong phòng chứa rượu làm lạnh tự động thuộc hầm rượu cá nhân.': 'Organize private wine tastings with Sommeliers (Wine tasting experts), in the automatically refrigerated wine room of your personal wine cellar.',
};

const htmlFiles = fs.readdirSync(enDir).filter(f => f.endsWith('.html'));

htmlFiles.forEach(file => {
    const filePath = path.join(enDir, file);
    let content = fs.readFileSync(filePath, 'utf8');

    for (const [vn, en] of Object.entries(globalDict)) {
        const regex = new RegExp(vn, 'g');
        content = content.replace(regex, en);
    }
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Deep translated ${file}`);
});
